<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork865-2023-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones. 

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage. 


Therefore if we can determine if the first stage will land, we can determine the cost of a launch. 

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

**Navigate to Go to UI screen** 

* Refer to this insruction in this <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sign%20up%20for%20IBM%20Cloud%20-%20Create%20Db2%20service%20instance%20-%20Get%20started%20with%20the%20Db2%20console/instructional-labs.md.html">link</a> for viewing  the  Go to UI screen. 


* Later click on **Data link(below SQL)**  in the Go to UI screen  and click on **Load Data** tab.  



* Later browse for the downloaded spacex file.



<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/browsefile.png" width="800">


* Once done select the schema andload the file.  


 <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload3.png" width="800">



If you are facing a problem in uploading the dataset (which is a csv file), you can follow the steps below to upload the .sql file instead of the CSV file:

* Download the file <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/Spacex%20.sql">Spacex.sql</a>

* Later click on **SQL** in the  **Go to UI Screen**.

* Use the **From file** option to browse for the **SQL** file and upload it.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/sqlfile.png">

* Once you upload the script,you can use the **Run All** option to run all the queries to insert the data.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/runall.png">

In [1]:
!pip install --force-reinstall ibm_db==3.1.0 ibm_db_sa==0.3.3
!pip install sqlalchemy==1.3.24
!pip uninstall ipython-sql -y
!pip install ipython-sql==0.4.1

Collecting ibm_db==3.1.0
  Downloading ibm_db-3.1.0.tar.gz (797 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 797.3/797.3 kB 30.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ibm_db_sa==0.3.3
  Downloading ibm_db_sa-0.3.3.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting sqlalchemy>=0.7.3
  Using cached SQLAlchemy-2.0.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
Collecting greenlet!=0.4.17
  Downloading greenlet-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (613 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.7/613.7 kB 32.4 MB/s eta 0:00:00
Collecting typing-extensions>=4.2.0
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Building wheels for collected packages: ibm_db, ibm_db_sa
  Building wheel for ibm_db (pyproject.toml) ... done
  Created wheel for ibm_db: filename=ibm_db-3.1.0-cp310-cp310-linux_x86_64.whl size=267276 sha256=e7db728c46cb21480bf255dfd2c56d724ec9c1cb2cf13ab56c60a9ccdcd9e70c
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/50/d7/3d/cf01ca490baa2f299aca0c791a2a5708d9b9676608374e2f31
  Building wheel for ibm_db_sa (setup.py) ... done
  Created wheel for ibm_db_sa: filename=ibm_db_sa-0.3.3-py3-none-any.whl size=27425 sha256=287c3bbe1a1458272632c642c5782bdfce004b6862d3ccd9f9d105c03c823d48
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/63/28/d7/aea2c85d7ff99e1e8dffc7424367812bf53659141c203f2c9a
Successfully built ibm_db ibm_db_sa
Installing collected packages: ibm_db, typing-extensions, greenlet, sqlalchemy, ibm_db_sa
  Attempting uninstall: ibm_db
    Found existing installation: ibm-db 3.1.3
    Uninstalling ibm-db-3.1.3:
      Successfully uninstalled ibm-db-3.1.3
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.3.0
    Uninstalling typing_extensions-4.3.0:
      Successfully uninstalled typing_extensions-4.3.0
  Attempting uninstall: greenlet
    Found existing installation: greenlet 1.1.1
    Uninstalling greenlet-1.1.1:
      Successfully uninstalled greenlet-1.1.1
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.9
    Uninstalling SQLAlchemy-2.0.9:
      Successfully uninstalled SQLAlchemy-2.0.9
  Attempting uninstall: ibm_db_sa
    Found existing installation: ibm-db-sa 0.3.8
    Uninstalling ibm-db-sa-0.3.8:
      Successfully uninstalled ibm-db-sa-0.3.8
Successfully installed greenlet-2.0.2 ibm_db-3.1.0 ibm_db_sa-0.3.3 sqlalchemy-2.0.9 typing-extensions-4.5.0
Collecting sqlalchemy==1.3.24
  Downloading SQLAlchemy-1.3.24.tar.gz (6.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 39.7 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.24-cp310-cp310-linux_x86_64.whl size=1219926 sha256=54aebef76b3dc91f6f7c165a66575e0ecaca4f78d06d8653a7999c8815d433fb
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/27/51/b3/3481e88d5a5ba95dd4aafedc9316774d941c4ba61cfb93add8
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.9
    Uninstalling SQLAlchemy-2.0.9:
      Successfully uninstalled SQLAlchemy-2.0.9
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.3.24 which is incompatible.
Successfully installed sqlalchemy-1.3.24
Found existing installation: ipython-sql 0.5.0
Uninstalling ipython-sql-0.5.0:
  Successfully uninstalled ipython-sql-0.5.0
Collecting ipython-sql==0.4.1
  Downloading ipython_sql-0.4.1-py3-none-any.whl (21 kB)
Collecting prettytable<1
  Downloading prettytable-0.7.2.zip (28 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ipython-genutils>=0.1.0 in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython-sql==0.4.1) (0.2.0)
Requirement already satisfied: sqlalchemy>=0.6.7 in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython-sql==0.4.1) (1.3.24)
Requirement already satisfied: six in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython-sql==0.4.1) (1.16.0)
Requirement already satisfied: sqlparse in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython-sql==0.4.1) (0.4.3)
Requirement already satisfied: ipython>=1.0 in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython-sql==0.4.1) (8.4.0)
Requirement already satisfied: traitlets>=5 in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (5.1.1)
Requirement already satisfied: pickleshare in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.7.5)
Requirement already satisfied: jedi>=0.16 in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.18.1)
Requirement already satisfied: pexpect>4.3 in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (4.8.0)
Requirement already satisfied: decorator in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (5.1.1)
Requirement already satisfied: backcall in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.2.0)
Requirement already satisfied: matplotlib-inline in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.1.6)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (3.0.20)
Requirement already satisfied: stack-data in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.2.0)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (2.11.2)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from ipython>=1.0->ipython-sql==0.4.1) (65.6.3)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from jedi>=0.16->ipython>=1.0->ipython-sql==0.4.1) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from pexpect>4.3->ipython>=1.0->ipython-sql==0.4.1) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=1.0->ipython-sql==0.4.1) (0.2.5)
Requirement already satisfied: executing in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from stack-data->ipython>=1.0->ipython-sql==0.4.1) (0.8.3)
Requirement already satisfied: asttokens in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from stack-data->ipython>=1.0->ipython-sql==0.4.1) (2.0.5)
Requirement already satisfied: pure-eval in /opt/conda/envs/Python-3.10/lib/python3.10/site-packages (from stack-data->ipython>=1.0->ipython-sql==0.4.1) (0.2.2)
Building wheels for collected packages: prettytable
  Building wheel for prettytable (setup.py) ... done
  Created wheel for prettytable: filename=prettytable-0.7.2-py3-none-any.whl size=13713 sha256=f779bb0361b338950ff61523a02ccc7b4f3a9914ef637a2c31042a3597b8bc64
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/25/4b/07/18c5d92824315576e478206ea69df34a9e31958f6143eb0e31
Successfully built prettytable

Installing collected packages: prettytable, ipython-sql
  Attempting uninstall: prettytable
    Found existing installation: prettytable 3.7.0
    Uninstalling prettytable-3.7.0:
      Successfully uninstalled prettytable-3.7.0
Successfully installed ipython-sql-0.4.1 prettytable-0.7.2

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [2]:
%load_ext sql



**DB2 magic in case of  UI service credentials.**



<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/servicecredentials.png" width="600">  

* Use the following format.

* Add security=SSL at the end

**%sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name?security=SSL**

In [8]:
import ibm_db
import pandas as pd
import datetime
# Connect to the DB2 database
dsn_driver = "{IBM DB2 ODBC DRIVER}"
dsn_database = 
dsn_hostname = 
dsn_port = 
dsn_protocol = "TCPIP"
dsn_uid = 
dsn_pwd = 
dsn_security = "SSL"
conn_str = (
    f"DRIVER={{{dsn_driver}}};"
    f"DATABASE={dsn_database};"
    f"HOSTNAME={dsn_hostname};"
    f"PORT={dsn_port};"
    f"PROTOCOL={dsn_protocol};"
    f"UID={dsn_uid};"
    f"PWD={dsn_pwd};"
    f"SECURITY={dsn_security};"
)

conn = ibm_db.connect(conn_str, "", "")

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [9]:
query = "SELECT DISTINCT LAUNCH_SITE FROM SPACEX"
stmt = ibm_db.exec_immediate(conn, query)
result = ibm_db.fetch_tuple(stmt)
while result:
    print(result[0])
    result = ibm_db.fetch_tuple(stmt)

CCAFS LC-40
CCAFS SLC-40
KSC LC-39A
VAFB SLC-4E


### Task 2


#####  Display 5 records where launch sites begin with the string 'KSC'

In [10]:
query = "SELECT * FROM SPACEX WHERE LAUNCH_SITE LIKE 'KSC%' FETCH FIRST 5 ROWS ONLY"
stmt = ibm_db.exec_immediate(conn, query)
result = ibm_db.fetch_both(stmt)
while result:
    print(result)
    result = ibm_db.fetch_both(stmt)

{'DATE': datetime.date(2017, 2, 19), 0: datetime.date(2017, 2, 19), 'TIME__UTC_': datetime.time(14, 39), 1: datetime.time(14, 39), 'BOOSTER_VERSION': 'F9 FT B1031.1', 2: 'F9 FT B1031.1', 'LAUNCH_SITE': 'KSC LC-39A', 3: 'KSC LC-39A', 'PAYLOAD': 'SpaceX CRS-10', 4: 'SpaceX CRS-10', 'PAYLOAD_MASS__KG_': 2490, 5: 2490, 'ORBIT': 'LEO (ISS)', 6: 'LEO (ISS)', 'CUSTOMER': 'NASA (CRS)', 7: 'NASA (CRS)', 'MISSION_OUTCOME': 'Success', 8: 'Success', 'LANDING__OUTCOME': 'Success (ground pad)', 9: 'Success (ground pad)'}
{'DATE': datetime.date(2017, 3, 16), 0: datetime.date(2017, 3, 16), 'TIME__UTC_': datetime.time(6, 0), 1: datetime.time(6, 0), 'BOOSTER_VERSION': 'F9 FT B1030', 2: 'F9 FT B1030', 'LAUNCH_SITE': 'KSC LC-39A', 3: 'KSC LC-39A', 'PAYLOAD': 'EchoStar 23', 4: 'EchoStar 23', 'PAYLOAD_MASS__KG_': 5600, 5: 5600, 'ORBIT': 'GTO', 6: 'GTO', 'CUSTOMER': 'EchoStar', 7: 'EchoStar', 'MISSION_OUTCOME': 'Success', 8: 'Success', 'LANDING__OUTCOME': 'No attempt', 9: 'No attempt'}
{'DATE': datetime.date(2017, 3, 30), 0: datetime.date(2017, 3, 30), 'TIME__UTC_': datetime.time(22, 27), 1: datetime.time(22, 27), 'BOOSTER_VERSION': 'F9 FT  B1021.2', 2: 'F9 FT  B1021.2', 'LAUNCH_SITE': 'KSC LC-39A', 3: 'KSC LC-39A', 'PAYLOAD': 'SES-10', 4: 'SES-10', 'PAYLOAD_MASS__KG_': 5300, 5: 5300, 'ORBIT': 'GTO', 6: 'GTO', 'CUSTOMER': 'SES', 7: 'SES', 'MISSION_OUTCOME': 'Success', 8: 'Success', 'LANDING__OUTCOME': 'Success (drone ship)', 9: 'Success (drone ship)'}
{'DATE': datetime.date(2017, 5, 1), 0: datetime.date(2017, 5, 1), 'TIME__UTC_': datetime.time(11, 15), 1: datetime.time(11, 15), 'BOOSTER_VERSION': 'F9 FT B1032.1', 2: 'F9 FT B1032.1', 'LAUNCH_SITE': 'KSC LC-39A', 3: 'KSC LC-39A', 'PAYLOAD': 'NROL-76', 4: 'NROL-76', 'PAYLOAD_MASS__KG_': 5300, 5: 5300, 'ORBIT': 'LEO', 6: 'LEO', 'CUSTOMER': 'NRO', 7: 'NRO', 'MISSION_OUTCOME': 'Success', 8: 'Success', 'LANDING__OUTCOME': 'Success (ground pad)', 9: 'Success (ground pad)'}
{'DATE': datetime.date(2017, 5, 15), 0: datetime.date(2017, 5, 15), 'TIME__UTC_': datetime.time(23, 21), 1: datetime.time(23, 21), 'BOOSTER_VERSION': 'F9 FT B1034', 2: 'F9 FT B1034', 'LAUNCH_SITE': 'KSC LC-39A', 3: 'KSC LC-39A', 'PAYLOAD': 'Inmarsat-5 F4', 4: 'Inmarsat-5 F4', 'PAYLOAD_MASS__KG_': 6070, 5: 6070, 'ORBIT': 'GTO', 6: 'GTO', 'CUSTOMER': 'Inmarsat', 7: 'Inmarsat', 'MISSION_OUTCOME': 'Success', 8: 'Success', 'LANDING__OUTCOME': 'No attempt', 9: 'No attempt'}

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [11]:
query = "SELECT SUM(PAYLOAD_MASS__KG_) FROM SPACEX WHERE CUSTOMER = 'NASA (CRS)'"
stmt = ibm_db.exec_immediate(conn, query)
result = ibm_db.fetch_tuple(stmt)
print(f"Total Payload Mass for NASA (CRS): {result[0]} kg")

Total Payload Mass for NASA (CRS): 45596 kg

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [13]:
query = "SELECT AVG(PAYLOAD_MASS__KG_) FROM SPACEX WHERE BOOSTER_VERSION = 'F9 v1.1'"
stmt = ibm_db.exec_immediate(conn, query)
result = ibm_db.fetch_tuple(stmt)
print(f"Average Payload Mass for F9 v1.1: {result[0]} kg")

Average Payload Mass for F9 v1.1: 2928 kg

### Task 5

##### List the date where the first successful landing outcome in drone ship was acheived.


_Hint:Use min function_

In [14]:
query = "SELECT MIN(DATE) FROM SPACEX WHERE LANDING__OUTCOME = 'Success (drone ship)'"
stmt = ibm_db.exec_immediate(conn, query)
result = ibm_db.fetch_both(stmt)
print(result[0])

2016-04-08

### Task 6

##### List the names of the boosters which have success in ground pad  and have payload mass greater than 4000 but less than 6000

In [15]:
query = "SELECT BOOSTER_VERSION FROM SPACEX WHERE MISSION_OUTCOME = 'Success' AND LANDING__OUTCOME = 'Success (ground pad)' AND PAYLOAD_MASS__KG_ > 4000 AND PAYLOAD_MASS__KG_ < 6000"
stmt = ibm_db.exec_immediate(conn, query)
result = ibm_db.fetch_tuple(stmt)
while result:
    print(result[0])
    result = ibm_db.fetch_tuple(stmt)

F9 FT B1032.1
F9 B4 B1040.1

### Task 7




##### List the total number of successful and failure mission outcomes

In [16]:
query = "SELECT MISSION_OUTCOME, COUNT(*) FROM SPACEX GROUP BY MISSION_OUTCOME"
stmt = ibm_db.exec_immediate(conn, query)
result = ibm_db.fetch_tuple(stmt)
while result:
    print(f"{result[0]}: {result[1]}")
    result = ibm_db.fetch_tuple(stmt)

Failure (in flight): 1
Success: 99
Success (payload status unclear): 1

### Task 8



##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [17]:
query = "SELECT BOOSTER_VERSION FROM SPACEX WHERE PAYLOAD_MASS__KG_ = (SELECT MAX(PAYLOAD_MASS__KG_) FROM SPACEX)"
stmt = ibm_db.exec_immediate(conn, query)
result = ibm_db.fetch_tuple(stmt)
while result:
    print(result[0])
    result = ibm_db.fetch_tuple(stmt)

F9 B5 B1048.4
F9 B5 B1049.4
F9 B5 B1051.3
F9 B5 B1056.4
F9 B5 B1048.5
F9 B5 B1051.4
F9 B5 B1049.5
F9 B5 B1060.2
F9 B5 B1058.3
F9 B5 B1051.6
F9 B5 B1060.3
F9 B5 B1049.7

### Task 9


##### List the records which will display the month names, succesful landing_outcomes in ground pad ,booster versions, launch_site for the months in year 2017

In [18]:
query = "SELECT TO_CHAR(DATE, 'MONTH'), LANDING__OUTCOME, BOOSTER_VERSION, LAUNCH_SITE FROM SPACEX WHERE DATE BETWEEN '2017-01-01' AND '2017-12-31' AND LANDING__OUTCOME = 'Success (ground pad)'"
stmt = ibm_db.exec_immediate(conn, query)
columns = [col[0] for col in ibm_db.fetch_tuple(stmt)]
data = []
row = ibm_db.fetch_tuple(stmt)
while row:
    data.append(row)
    row = ibm_db.fetch_tuple(stmt)
print(pd.DataFrame(data, columns=columns))

           F                     S               F             K
0        MAY  Success (ground pad)   F9 FT B1032.1    KSC LC-39A
1       JUNE  Success (ground pad)   F9 FT B1035.1    KSC LC-39A
2     AUGUST  Success (ground pad)   F9 B4 B1039.1    KSC LC-39A
3  SEPTEMBER  Success (ground pad)   F9 B4 B1040.1    KSC LC-39A
4   DECEMBER  Success (ground pad)  F9 FT  B1035.2  CCAFS SLC-40

### Task 10




##### Rank the  count of  successful landing_outcomes between the date 2010-06-04 and 2017-03-20 in descending order.

In [19]:
query = "SELECT LANDING__OUTCOME, COUNT(*) FROM SPACEX WHERE MISSION_OUTCOME = 'Success' AND DATE BETWEEN '2010-06-04' AND '2017-03-20' GROUP BY LANDING__OUTCOME ORDER BY COUNT(*) DESC"
stmt = ibm_db.exec_immediate(conn, query)
result = ibm_db.fetch_tuple(stmt)
while result:
    print(f"{result[0]}: {result[1]}")
    result = ibm_db.fetch_tuple(stmt)

No attempt: 10
Failure (drone ship): 5
Success (drone ship): 5
Controlled (ocean): 3
Success (ground pad): 3
Failure (parachute): 2
Uncontrolled (ocean): 2

### Reference Links

* <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%203/LAB-String_Patterns_Sorting_Grouping.md.html">Hands-on Lab : String Patterns, Sorting and Grouping</a>  

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html">Hands-on Lab: Built-in functions</a>

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*  <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

## Change log
| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2021-10-12 | 0.4 |Lakshmi Holla | Changed markdown|
| 2021-08-24 | 0.3 |Lakshmi Holla | Added library update|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>